import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy - CalBot",
  description: "Privacy Policy for CalBot, an AI calorie tracker in Telegram."
};

export default function PrivacyPolicyPage() {
  return (
    <main className="legalPage">
      <nav className="legalTopNav" aria-label="Legal navigation">
        <Link className="brand" href="/">
          <span className="brandMark">C</span>
          <span>CalBot</span>
        </Link>
        <div>
          <Link href="/terms">Terms</Link>
          <Link aria-current="page" href="/privacy">
            Privacy
          </Link>
          <Link href="/refund">Refund</Link>
        </div>
      </nav>

      <article className="legalDocument">
        <header className="legalHeader">
          <h1>Privacy Policy</h1>
          <p>Effective date: 1 May 2026</p>
        </header>

        <section>
          <p>
            This Privacy Policy explains how Pomo Cowork, operating CalBot
            (&quot;CalBot&quot;, &quot;we&quot;, &quot;us&quot;), collects, uses, shares, and protects
            information when you use our website, Telegram bot, subscriptions, and
            related services (collectively, the &quot;Service&quot;).
          </p>

          <div>
            <h2>1. Scope</h2>
            <p>
              This Policy applies to information processed by CalBot in connection with
              the Service. It does not cover Telegram, payment processors, AI model
              providers, or other third-party websites, services, or apps you may access
              through links or integrations.
            </p>
          </div>

          <div>
            <h2>2. Information we collect</h2>
            <ul>
              <li>
                <strong>Telegram account data:</strong> Telegram user ID, username,
                display name, language, and account-related identifiers provided by
                Telegram.
              </li>
              <li>
                <strong>Service content:</strong> food photos, meal descriptions,
                messages, nutrition logs, preferences, targets, and settings you submit
                to the Service.
              </li>
              <li>
                <strong>Nutrition data:</strong> estimated calories, macros, meal
                history, usage limits, subscription tier, and analytics generated by the
                Service.
              </li>
              <li>
                <strong>Support data:</strong> messages you send to support and related
                metadata, such as time, account ID, and issue details.
              </li>
              <li>
                <strong>Usage data:</strong> feature usage, interaction events,
                timestamps, approximate location derived from IP address, and
                performance data.
              </li>
              <li>
                <strong>Device and log data:</strong> IP address, user agent, device
                type, OS version, language, error logs, and diagnostic logs.
              </li>
              <li>
                <strong>Payment data:</strong> subscription status, plan, billing cycle,
                transaction identifiers, receipts, and refund status. Payment card
                details are processed by the payment provider; we do not store full card
                numbers.
              </li>
              <li>
                <strong>Cookies and similar technologies:</strong> used on the website
                for security, preferences, and analytics where enabled.
              </li>
            </ul>
          </div>

          <div>
            <h2>3. How we use information</h2>
            <ul>
              <li>Provide, operate, and maintain the Service.</li>
              <li>Analyze food photos and descriptions and return nutrition estimates.</li>
              <li>Save meal history, preferences, limits, subscription status, and stats.</li>
              <li>Process subscriptions, billing, refunds, and payment fraud prevention.</li>
              <li>Monitor, debug, and improve performance, reliability, and features.</li>
              <li>Secure the Service, detect abuse, and enforce our terms.</li>
              <li>Send service-related messages, such as receipts or important changes.</li>
              <li>Respond to support requests and resolve issues.</li>
            </ul>
          </div>

          <div>
            <h2>4. Legal bases (EEA/UK, where applicable)</h2>
            <ul>
              <li>
                <strong>Contract:</strong> to provide the Service and subscriptions you
                request.
              </li>
              <li>
                <strong>Legitimate interests:</strong> to secure, maintain, and improve
                the Service, prevent fraud, and provide support.
              </li>
              <li>
                <strong>Consent:</strong> where required for certain cookies, analytics,
                or optional communications.
              </li>
              <li>
                <strong>Legal obligations:</strong> accounting, tax, compliance, and
                lawful request requirements.
              </li>
            </ul>
          </div>

          <div>
            <h2>5. How we share information</h2>
            <p>We do not sell your personal information. We may share information:</p>
            <ul>
              <li>
                <strong>With service providers:</strong> hosting, databases, analytics,
                error monitoring, support tools, payment processing, and AI model
                providers, only as needed to provide the Service.
              </li>
              <li>
                <strong>With Telegram:</strong> the Service operates through Telegram, so
                your Telegram use remains subject to Telegram&apos;s own terms and privacy
                policy.
              </li>
              <li>
                <strong>For legal reasons:</strong> to comply with lawful requests,
                protect rights and safety, and enforce our terms.
              </li>
              <li>
                <strong>Business transfers:</strong> in connection with a merger,
                acquisition, financing, or sale of assets, with appropriate safeguards.
              </li>
            </ul>
          </div>

          <div>
            <h2>6. International transfers</h2>
            <p>
              We may process and store information in countries other than your own.
              Where required, we use appropriate safeguards for cross-border transfers,
              such as contractual protections.
            </p>
          </div>

          <div>
            <h2>7. Data retention</h2>
            <p>
              We retain information for as long as necessary to provide the Service and
              for legitimate and essential business purposes, such as security, dispute
              resolution, enforcing agreements, accounting, tax, and compliance. You can
              request deletion as described below.
            </p>
          </div>

          <div>
            <h2>8. Security</h2>
            <p>
              We use reasonable administrative, technical, and organizational measures to
              protect information. No method of transmission or storage is 100% secure.
            </p>
          </div>

          <div>
            <h2>9. Your rights and choices</h2>
            <ul>
              <li>
                <strong>Access, correction, deletion:</strong> you may request access
                to, correction of, or deletion of your personal data.
              </li>
              <li>
                <strong>Objection or restriction:</strong> you may object to or request
                restriction of certain processing where applicable.
              </li>
              <li>
                <strong>Portability:</strong> you may request a copy of certain data in a
                portable format where applicable.
              </li>
              <li>
                <strong>Withdraw consent:</strong> where processing is based on consent,
                you can withdraw it at any time.
              </li>
            </ul>
            <p>
              To make a request, contact us through the CalBot support flow in Telegram.
              We may need to verify your identity.
            </p>
          </div>

          <div>
            <h2>10. Children</h2>
            <p>
              The Service is not intended for children under 16, or the age of digital
              consent in your country. If you believe a child provided personal data,
              contact us through the CalBot support flow in Telegram.
            </p>
          </div>

          <div>
            <h2>11. Cookies</h2>
            <p>
              We may use cookies and similar technologies on the website for security,
              preferences, and analytics. Where applicable, you can control cookies via
              your browser settings. Disabling cookies may affect parts of the website.
            </p>
          </div>

          <div>
            <h2>12. AI processing</h2>
            <p>
              Food photos, meal descriptions, and related content may be processed by AI
              model providers to generate nutrition estimates. We use this processing to
              provide the Service and do not treat AI output as medical or professional
              nutrition advice.
            </p>
          </div>

          <div>
            <h2>13. Changes to this Policy</h2>
            <p>
              We may update this Policy from time to time. If changes are material, we
              will provide notice in the Service, on the website, or through another
              reasonable channel. The effective date above indicates when this Policy was
              last updated.
            </p>
          </div>

          <div>
            <h2>14. Contact</h2>
            <p>
              If you have questions about this Policy or our privacy practices, contact
              us through the CalBot support flow in Telegram.
            </p>
          </div>
        </section>
      </article>
    </main>
  );
}
